language: node_js
node_js:
 - 10.15.3
cache:
 directories:
 - node_modules
env:
 global:
   - CC_TEST_REPORTER_ID=d1409c1d684f1eb5aef793ac276677bd56fd04bb25d34d894f36f1af65292c39
before_script:
 - export CC_TEST_REPORTER_ID=d1409c1d684f1eb5aef793ac276677bd56fd04bb25d34d894f36f1af65292c39
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
script:
 - npm i
 - npx jest -u --coverage
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
