language: node_js
node_js:
 - 10.15.3
cache:
 directories:
 - node_modules
env:
 global:
   - CC_TEST_REPORTER_ID=d384475cae3fd0aa12a227104b003170448aaee222f4eb5324565a33fcba08a3
before_script:
 - export CC_TEST_REPORTER_ID=d384475cae3fd0aa12a227104b003170448aaee222f4eb5324565a33fcba08a3
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
script:
 - npm i jest
 - npx jest -u --coverage
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
